apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 10
  #minReadySeconds: 15
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: httpd:alpine3.18
          name: httpd
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: 80
          #  initialDelaySeconds: 5
          #  periodSeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
